// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/group.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Group struct {
	// The unique ID of a group.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The group's display name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The group's email address.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// An extended description to help users determine the purpose of a group.
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_291a6f2e016f8fe9, []int{0}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Group) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Member struct {
	// The unique ID of the group member.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The member's email address.
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Status of member. Acceptable values are:
	// "ACTIVE"
	// "ARCHIVED"
	// "SUSPENDED"
	// "UNKNOWN"
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_291a6f2e016f8fe9, []int{1}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Member) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Member) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ListGroupsRequest struct {
	// Maximum number of results to return. Acceptable values are 1 to 200, inclusive.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token to specify next page in the list.
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsRequest) Reset()         { *m = ListGroupsRequest{} }
func (m *ListGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroupsRequest) ProtoMessage()    {}
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_291a6f2e016f8fe9, []int{2}
}

func (m *ListGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsRequest.Unmarshal(m, b)
}
func (m *ListGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsRequest.Marshal(b, m, deterministic)
}
func (m *ListGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsRequest.Merge(m, src)
}
func (m *ListGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroupsRequest.Size(m)
}
func (m *ListGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsRequest proto.InternalMessageInfo

func (m *ListGroupsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListGroupsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListGroupsResponse struct {
	// List of group objects.
	Groups []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	// Token used to access next page of this result.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsResponse) Reset()         { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()    {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_291a6f2e016f8fe9, []int{3}
}

func (m *ListGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsResponse.Unmarshal(m, b)
}
func (m *ListGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsResponse.Marshal(b, m, deterministic)
}
func (m *ListGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsResponse.Merge(m, src)
}
func (m *ListGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupsResponse.Size(m)
}
func (m *ListGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsResponse proto.InternalMessageInfo

func (m *ListGroupsResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *ListGroupsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetGroupRequest struct {
	// The field will contain name of the resource requested.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupRequest) Reset()         { *m = GetGroupRequest{} }
func (m *GetGroupRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupRequest) ProtoMessage()    {}
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_291a6f2e016f8fe9, []int{4}
}

func (m *GetGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupRequest.Unmarshal(m, b)
}
func (m *GetGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupRequest.Merge(m, src)
}
func (m *GetGroupRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupRequest.Size(m)
}
func (m *GetGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupRequest proto.InternalMessageInfo

func (m *GetGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateGroupRequest struct {
	// The group to create.
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_291a6f2e016f8fe9, []int{5}
}

func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (m *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(m, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

func (m *CreateGroupRequest) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type DeleteGroupRequest struct {
	// The resource name of the group to be deleted.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupRequest) Reset()         { *m = DeleteGroupRequest{} }
func (m *DeleteGroupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupRequest) ProtoMessage()    {}
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_291a6f2e016f8fe9, []int{6}
}

func (m *DeleteGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupRequest.Unmarshal(m, b)
}
func (m *DeleteGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupRequest.Marshal(b, m, deterministic)
}
func (m *DeleteGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupRequest.Merge(m, src)
}
func (m *DeleteGroupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupRequest.Size(m)
}
func (m *DeleteGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupRequest proto.InternalMessageInfo

func (m *DeleteGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListMembersRequest struct {
	// The parent resource name.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Maximum number of results to return. Acceptable values are 1 to 200, inclusive.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token to specify the next page in the list.
	PageToken            string   `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMembersRequest) Reset()         { *m = ListMembersRequest{} }
func (m *ListMembersRequest) String() string { return proto.CompactTextString(m) }
func (*ListMembersRequest) ProtoMessage()    {}
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_291a6f2e016f8fe9, []int{7}
}

func (m *ListMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMembersRequest.Unmarshal(m, b)
}
func (m *ListMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMembersRequest.Marshal(b, m, deterministic)
}
func (m *ListMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMembersRequest.Merge(m, src)
}
func (m *ListMembersRequest) XXX_Size() int {
	return xxx_messageInfo_ListMembersRequest.Size(m)
}
func (m *ListMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMembersRequest proto.InternalMessageInfo

func (m *ListMembersRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListMembersRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListMembersRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListMembersResponse struct {
	// List of member objects.
	Members []*Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	// Token used to access next page of this result.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMembersResponse) Reset()         { *m = ListMembersResponse{} }
func (m *ListMembersResponse) String() string { return proto.CompactTextString(m) }
func (*ListMembersResponse) ProtoMessage()    {}
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_291a6f2e016f8fe9, []int{8}
}

func (m *ListMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMembersResponse.Unmarshal(m, b)
}
func (m *ListMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMembersResponse.Marshal(b, m, deterministic)
}
func (m *ListMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMembersResponse.Merge(m, src)
}
func (m *ListMembersResponse) XXX_Size() int {
	return xxx_messageInfo_ListMembersResponse.Size(m)
}
func (m *ListMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMembersResponse proto.InternalMessageInfo

func (m *ListMembersResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *ListMembersResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetMemberRequest struct {
	// The field will contain name of the resource requested.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemberRequest) Reset()         { *m = GetMemberRequest{} }
func (m *GetMemberRequest) String() string { return proto.CompactTextString(m) }
func (*GetMemberRequest) ProtoMessage()    {}
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_291a6f2e016f8fe9, []int{9}
}

func (m *GetMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberRequest.Unmarshal(m, b)
}
func (m *GetMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberRequest.Marshal(b, m, deterministic)
}
func (m *GetMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberRequest.Merge(m, src)
}
func (m *GetMemberRequest) XXX_Size() int {
	return xxx_messageInfo_GetMemberRequest.Size(m)
}
func (m *GetMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberRequest proto.InternalMessageInfo

func (m *GetMemberRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateMemberRequest struct {
	// The parent resource name where the member is to be created.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The member to create.
	Member               *Member  `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMemberRequest) Reset()         { *m = CreateMemberRequest{} }
func (m *CreateMemberRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMemberRequest) ProtoMessage()    {}
func (*CreateMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_291a6f2e016f8fe9, []int{10}
}

func (m *CreateMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMemberRequest.Unmarshal(m, b)
}
func (m *CreateMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMemberRequest.Marshal(b, m, deterministic)
}
func (m *CreateMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMemberRequest.Merge(m, src)
}
func (m *CreateMemberRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMemberRequest.Size(m)
}
func (m *CreateMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMemberRequest proto.InternalMessageInfo

func (m *CreateMemberRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateMemberRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type DeleteMemberRequest struct {
	// The resource name of the member to be deleted.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMemberRequest) Reset()         { *m = DeleteMemberRequest{} }
func (m *DeleteMemberRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMemberRequest) ProtoMessage()    {}
func (*DeleteMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_291a6f2e016f8fe9, []int{11}
}

func (m *DeleteMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMemberRequest.Unmarshal(m, b)
}
func (m *DeleteMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMemberRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMemberRequest.Merge(m, src)
}
func (m *DeleteMemberRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMemberRequest.Size(m)
}
func (m *DeleteMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMemberRequest proto.InternalMessageInfo

func (m *DeleteMemberRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Group)(nil), "kordevaus.Group")
	proto.RegisterType((*Member)(nil), "kordevaus.Member")
	proto.RegisterType((*ListGroupsRequest)(nil), "kordevaus.ListGroupsRequest")
	proto.RegisterType((*ListGroupsResponse)(nil), "kordevaus.ListGroupsResponse")
	proto.RegisterType((*GetGroupRequest)(nil), "kordevaus.GetGroupRequest")
	proto.RegisterType((*CreateGroupRequest)(nil), "kordevaus.CreateGroupRequest")
	proto.RegisterType((*DeleteGroupRequest)(nil), "kordevaus.DeleteGroupRequest")
	proto.RegisterType((*ListMembersRequest)(nil), "kordevaus.ListMembersRequest")
	proto.RegisterType((*ListMembersResponse)(nil), "kordevaus.ListMembersResponse")
	proto.RegisterType((*GetMemberRequest)(nil), "kordevaus.GetMemberRequest")
	proto.RegisterType((*CreateMemberRequest)(nil), "kordevaus.CreateMemberRequest")
	proto.RegisterType((*DeleteMemberRequest)(nil), "kordevaus.DeleteMemberRequest")
}

func init() {
	proto.RegisterFile("pb/group.proto", fileDescriptor_291a6f2e016f8fe9)
}

var fileDescriptor_291a6f2e016f8fe9 = []byte{
	// 690 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x55, 0xdc, 0xc6, 0x5f, 0x33, 0xc9, 0xd7, 0x9f, 0x09, 0x94, 0xe0, 0xb4, 0xa5, 0xb2, 0xd4,
	0x92, 0x16, 0x11, 0xb7, 0x45, 0xbd, 0xa9, 0xe0, 0x82, 0xdf, 0xde, 0x80, 0x40, 0x29, 0x48, 0x80,
	0x84, 0x2a, 0x27, 0x99, 0xa6, 0xa6, 0x89, 0x6d, 0xbc, 0x9b, 0x0a, 0x8a, 0xb8, 0xe1, 0x15, 0x78,
	0x2b, 0xae, 0x90, 0x78, 0x05, 0x1e, 0x04, 0x79, 0x77, 0x9d, 0xae, 0x63, 0x27, 0xe5, 0xae, 0x3b,
	0x33, 0x3d, 0xe7, 0xcc, 0x99, 0x13, 0xc3, 0x7c, 0xd8, 0x76, 0x7a, 0x51, 0x30, 0x0c, 0x9b, 0x61,
	0x14, 0xf0, 0x00, 0x4b, 0x67, 0x41, 0xd4, 0xa5, 0x73, 0x77, 0xc8, 0xac, 0x95, 0x5e, 0x10, 0xf4,
	0xfa, 0xe4, 0xb8, 0xa1, 0xe7, 0xb8, 0xbe, 0x1f, 0x70, 0x97, 0x7b, 0x81, 0xcf, 0xe4, 0xa0, 0x75,
	0x43, 0xeb, 0x76, 0xfa, 0x1e, 0xf9, 0x5c, 0x35, 0xea, 0xaa, 0x21, 0x5e, 0xed, 0xe1, 0x89, 0x43,
	0x83, 0x90, 0x7f, 0x91, 0x4d, 0xbb, 0x03, 0xc5, 0xc3, 0x98, 0x0d, 0xe7, 0xc1, 0xf0, 0xba, 0xb5,
	0xc2, 0x7a, 0xa1, 0x51, 0x6a, 0x19, 0x5e, 0x17, 0x11, 0x66, 0x7d, 0x77, 0x40, 0x35, 0x43, 0x54,
	0xc4, 0xdf, 0x78, 0x0d, 0x8a, 0x34, 0x70, 0xbd, 0x7e, 0x6d, 0x46, 0x14, 0xe5, 0x03, 0xd7, 0xa1,
	0xdc, 0x25, 0xd6, 0x89, 0xbc, 0x30, 0x96, 0x53, 0x9b, 0x15, 0x3d, 0xbd, 0x64, 0x3f, 0x03, 0xf3,
	0x05, 0x0d, 0xda, 0x14, 0x65, 0x58, 0x46, 0x88, 0x86, 0x8e, 0xb8, 0x0c, 0x26, 0xe3, 0x2e, 0x1f,
	0x32, 0x45, 0xa4, 0x5e, 0xf6, 0x4b, 0x58, 0x7a, 0xee, 0x31, 0x2e, 0x04, 0xb3, 0x16, 0x7d, 0x1a,
	0x12, 0xe3, 0x58, 0x87, 0x52, 0xe8, 0xf6, 0xe8, 0x98, 0x79, 0x17, 0x24, 0x90, 0x8b, 0xad, 0xb9,
	0xb8, 0x70, 0xe4, 0x5d, 0x10, 0xae, 0x02, 0x88, 0x26, 0x0f, 0xce, 0xc8, 0x57, 0x24, 0x62, 0xfc,
	0x75, 0x5c, 0xb0, 0x4f, 0x00, 0x75, 0x40, 0x16, 0x06, 0x3e, 0x23, 0x6c, 0x80, 0x29, 0x2e, 0xc0,
	0x6a, 0x85, 0xf5, 0x99, 0x46, 0x79, 0x6f, 0xb1, 0x39, 0xba, 0x41, 0x53, 0x8c, 0xb6, 0x54, 0x1f,
	0x37, 0x61, 0xc1, 0xa7, 0xcf, 0xfc, 0x38, 0xc3, 0xf1, 0x7f, 0x5c, 0x7e, 0x35, 0xe2, 0xd9, 0x80,
	0x85, 0x43, 0x92, 0x34, 0x89, 0xec, 0xc4, 0xdf, 0xc2, 0xa5, 0xbf, 0xf6, 0x7d, 0xc0, 0xc7, 0x11,
	0xb9, 0x9c, 0x52, 0x93, 0x9b, 0x50, 0x14, 0x74, 0x62, 0x34, 0x4f, 0x8d, 0x6c, 0xdb, 0x0d, 0xc0,
	0x27, 0xd4, 0xa7, 0xb1, 0xff, 0xce, 0xe3, 0x39, 0x95, 0x6b, 0xcb, 0x9b, 0x8c, 0x8c, 0x5c, 0x06,
	0x33, 0x74, 0x23, 0xf2, 0xb9, 0x9a, 0x55, 0xaf, 0xb4, 0xc1, 0xc6, 0x54, 0x83, 0x67, 0xc6, 0x0d,
	0xfe, 0x08, 0xd5, 0x14, 0x93, 0x72, 0xf8, 0x0e, 0xfc, 0x37, 0x90, 0x25, 0x65, 0xf1, 0x92, 0xb6,
	0x94, 0x1c, 0x6e, 0x25, 0x13, 0xff, 0x6c, 0xf2, 0x26, 0x2c, 0x1e, 0x92, 0xa2, 0x9a, 0xb6, 0xfd,
	0x5b, 0xa8, 0x4a, 0x97, 0xd3, 0xa3, 0x93, 0xd6, 0xdf, 0x02, 0x53, 0x2a, 0x11, 0xac, 0xb9, 0x52,
	0xd5, 0x80, 0xbd, 0x05, 0x55, 0x79, 0x81, 0x2b, 0x45, 0xec, 0xfd, 0x32, 0xa1, 0x22, 0xee, 0x74,
	0x44, 0xd1, 0xb9, 0xd7, 0x21, 0xfc, 0x00, 0x70, 0x19, 0x45, 0x5c, 0xd1, 0x48, 0x32, 0x91, 0xb7,
	0x56, 0x27, 0x74, 0xa5, 0xbb, 0x36, 0x7e, 0xff, 0xfd, 0xe7, 0x87, 0x51, 0x41, 0x70, 0xce, 0x77,
	0x1d, 0x95, 0xd4, 0x37, 0x30, 0x97, 0x24, 0x10, 0x2d, 0x3d, 0x41, 0xe9, 0x58, 0x5a, 0x99, 0x74,
	0xd9, 0x75, 0x81, 0x76, 0x1d, 0xab, 0x31, 0xda, 0xd7, 0x58, 0xfc, 0x03, 0x89, 0xe9, 0x6c, 0x7f,
	0xc3, 0x77, 0x50, 0xd6, 0x12, 0x8b, 0xba, 0xb0, 0x6c, 0x92, 0x73, 0xc0, 0x6f, 0x0a, 0xf0, 0xaa,
	0xad, 0x49, 0x3d, 0x90, 0x71, 0x46, 0x17, 0xca, 0x5a, 0x9c, 0x53, 0xd0, 0xd9, 0x98, 0x5b, 0xcb,
	0x4d, 0xf9, 0x95, 0x6b, 0x26, 0x5f, 0xb9, 0xe6, 0xd3, 0xf8, 0x2b, 0x97, 0xa8, 0xdf, 0xce, 0x55,
	0xcf, 0xa0, 0xac, 0xa5, 0x13, 0xc7, 0x6d, 0x4d, 0xff, 0x3e, 0xac, 0xb5, 0x49, 0x6d, 0x65, 0xfb,
	0x86, 0xa0, 0xba, 0x85, 0xab, 0x82, 0x4a, 0xa6, 0xe7, 0x92, 0xcc, 0x49, 0xe2, 0xdc, 0x86, 0xd2,
	0x28, 0xa6, 0x58, 0x4f, 0x9f, 0x22, 0x95, 0x1b, 0x2b, 0x9b, 0xb4, 0x31, 0x8e, 0xd4, 0x3a, 0x09,
	0x41, 0xbc, 0x58, 0x08, 0x15, 0x3d, 0xe2, 0xb8, 0x96, 0xb9, 0xcb, 0x95, 0x4c, 0x77, 0x05, 0xd3,
	0x6d, 0x7b, 0xfa, 0x36, 0x07, 0x2a, 0xfa, 0x38, 0x80, 0x8a, 0x1e, 0xfd, 0x14, 0x63, 0xce, 0x6f,
	0x62, 0xe2, 0xbd, 0xd4, 0x82, 0xdb, 0xd3, 0x17, 0xb4, 0xf0, 0xe7, 0xc3, 0x85, 0x7e, 0xd0, 0x71,
	0xfb, 0xa7, 0x01, 0xe3, 0x07, 0xfb, 0x3b, 0x3b, 0xfb, 0xbb, 0x8f, 0x66, 0xdf, 0x1b, 0x61, 0xbb,
	0x6d, 0x0a, 0xc0, 0x7b, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x9e, 0x06, 0x3c, 0x48, 0x07,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GroupServiceClient is the client API for GroupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GroupServiceClient interface {
	// Retrieve all groups.
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	// Retrieves a group's properties.
	GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*Group, error)
	// Creates a group.
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*Group, error)
	// Deletes a group.
	DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Retrieves a paginated list of all members in a group.
	ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
	// Retrieves a group member's properties.
	GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*Member, error)
	// Adds a user to the specified group.
	CreateMember(ctx context.Context, in *CreateMemberRequest, opts ...grpc.CallOption) (*Member, error)
	// Removes a member from a group.
	DeleteMember(ctx context.Context, in *DeleteMemberRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type groupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupServiceClient(cc grpc.ClientConnInterface) GroupServiceClient {
	return &groupServiceClient{cc}
}

func (c *groupServiceClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, "/kordevaus.GroupService/ListGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/kordevaus.GroupService/GetGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/kordevaus.GroupService/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/kordevaus.GroupService/DeleteGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, "/kordevaus.GroupService/ListMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*Member, error) {
	out := new(Member)
	err := c.cc.Invoke(ctx, "/kordevaus.GroupService/GetMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) CreateMember(ctx context.Context, in *CreateMemberRequest, opts ...grpc.CallOption) (*Member, error) {
	out := new(Member)
	err := c.cc.Invoke(ctx, "/kordevaus.GroupService/CreateMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) DeleteMember(ctx context.Context, in *DeleteMemberRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/kordevaus.GroupService/DeleteMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupServiceServer is the server API for GroupService service.
type GroupServiceServer interface {
	// Retrieve all groups.
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	// Retrieves a group's properties.
	GetGroup(context.Context, *GetGroupRequest) (*Group, error)
	// Creates a group.
	CreateGroup(context.Context, *CreateGroupRequest) (*Group, error)
	// Deletes a group.
	DeleteGroup(context.Context, *DeleteGroupRequest) (*empty.Empty, error)
	// Retrieves a paginated list of all members in a group.
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error)
	// Retrieves a group member's properties.
	GetMember(context.Context, *GetMemberRequest) (*Member, error)
	// Adds a user to the specified group.
	CreateMember(context.Context, *CreateMemberRequest) (*Member, error)
	// Removes a member from a group.
	DeleteMember(context.Context, *DeleteMemberRequest) (*empty.Empty, error)
}

// UnimplementedGroupServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGroupServiceServer struct {
}

func (*UnimplementedGroupServiceServer) ListGroups(ctx context.Context, req *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroups not implemented")
}
func (*UnimplementedGroupServiceServer) GetGroup(ctx context.Context, req *GetGroupRequest) (*Group, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroup not implemented")
}
func (*UnimplementedGroupServiceServer) CreateGroup(ctx context.Context, req *CreateGroupRequest) (*Group, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (*UnimplementedGroupServiceServer) DeleteGroup(ctx context.Context, req *DeleteGroupRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (*UnimplementedGroupServiceServer) ListMembers(ctx context.Context, req *ListMembersRequest) (*ListMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMembers not implemented")
}
func (*UnimplementedGroupServiceServer) GetMember(ctx context.Context, req *GetMemberRequest) (*Member, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMember not implemented")
}
func (*UnimplementedGroupServiceServer) CreateMember(ctx context.Context, req *CreateMemberRequest) (*Member, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMember not implemented")
}
func (*UnimplementedGroupServiceServer) DeleteMember(ctx context.Context, req *DeleteMemberRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMember not implemented")
}

func RegisterGroupServiceServer(s *grpc.Server, srv GroupServiceServer) {
	s.RegisterService(&_GroupService_serviceDesc, srv)
}

func _GroupService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kordevaus.GroupService/ListGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kordevaus.GroupService/GetGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetGroup(ctx, req.(*GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kordevaus.GroupService/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kordevaus.GroupService/DeleteGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).DeleteGroup(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kordevaus.GroupService/ListMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ListMembers(ctx, req.(*ListMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kordevaus.GroupService/GetMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetMember(ctx, req.(*GetMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_CreateMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).CreateMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kordevaus.GroupService/CreateMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).CreateMember(ctx, req.(*CreateMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_DeleteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).DeleteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kordevaus.GroupService/DeleteMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).DeleteMember(ctx, req.(*DeleteMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GroupService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kordevaus.GroupService",
	HandlerType: (*GroupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGroups",
			Handler:    _GroupService_ListGroups_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _GroupService_GetGroup_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _GroupService_CreateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _GroupService_DeleteGroup_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _GroupService_ListMembers_Handler,
		},
		{
			MethodName: "GetMember",
			Handler:    _GroupService_GetMember_Handler,
		},
		{
			MethodName: "CreateMember",
			Handler:    _GroupService_CreateMember_Handler,
		},
		{
			MethodName: "DeleteMember",
			Handler:    _GroupService_DeleteMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/group.proto",
}
